version: 2
updates:
  - package-ecosystem: "gradle"  
    directory: "/"  
    schedule:
      interval: "daily"
      time: "21:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "mrcsxsiq"
